# Generated by Django 5.0.4 on 2024-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busowner',
            name='tin_number',
            field=models.IntegerField(unique=True),
        ),
    ]
