# Generated by Django 5.0.4 on 2024-04-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('phone', models.CharField(max_length=15)),
                ('passenger_id', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('f_name', models.CharField(blank=True, max_length=100, null=True)),
                ('l_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('image_size', models.IntegerField()),
                ('image_path', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('plate_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seats_number', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.busmanager')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.CharField(max_length=30)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.busmanager')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('station', models.CharField(max_length=100)),
                ('route_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('starting_point', models.EmailField(blank=True, max_length=254, null=True)),
                ('destination', models.CharField(max_length=100)),
                ('via', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('buses', models.ManyToManyField(related_name='routes', to='Accounts.bus')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.busmanager')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('seatNo', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.route')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.passenger')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
