# Generated by Django 5.0.4 on 2024-04-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_rename_uploadimage_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='passenger_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
