# Generated by Django 5.0.4 on 2024-04-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_ticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('user_token', models.TextField()),
                ('dev_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTicketNotification',
            fields=[
                ('doc_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.usernotification')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.ticket')),
            ],
        ),
    ]
